---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ name }}-charm
  name: {{ name }}-charm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ name }}-charm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ name }}-charm
    spec:
      serviceAccountName: {{ name }}-charm
      containers:
      - image: quay.io/dexidp/dex:v2.22.0
        name: dex
        command: ["dex", "serve", "/etc/dex/cfg/config.yaml"]
        ports:
        - name: http
          containerPort: {{ port }}
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        env:
          - name: KUBERNETES_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      volumes:
      - name: config
        configMap:
          name: {{ name }}-charm
          items:
          - key: config.yaml
            path: config.yaml
